---
title: LOLAPPS

exclude: ['/Gemfile', '/Makefile', '/README.md']

permalink: pretty

collections:
  lolapps:
    output: true

defaults:
  - scope:
      path: '_lolapps'
    values:
      layout: 'app'
